name: Build OpenWrt with OpenSync

on:
  push:
    branches: [ uCentral-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ['cig_wf188', 'cig_wf194c', 'cig_wf160d.yml', 'edgecore_eap101', 'edgecore_eap102', 'edgecore_ecs4100-12ph', 'edgecore_ecw5211', 'linksys_e8450', 'tplink_cpe210_v3', 'linksys_ea8300', 'tplink_eap620', 'tplink_eap660', 'zyxel_gs1900-10hp']

    steps:
    - uses: actions/checkout@v2

    - name: Build image for ${{ matrix.target }}
      id: build
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        make -j TARGET=${{ matrix.target }}

    - name: Package and upload image for ${{ matrix.target }}
      env:
          GH_BUILD_USERNAME: ${{ secrets.GH_BUILD_USERNAME }}
          GH_BUILD_PASSWORD: ${{ secrets.GH_BUILD_PASSWORD }}
          ARTIFACTORY_USERNAME: cicd-indoor-main
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        LOWERCASE_TARGET=`echo ${{ matrix.target }} | tr '[:upper:]' '[:lower:]'`
        HASH=$(git rev-parse --short HEAD)
        TAR_NAME="$LOWERCASE_TARGET-$BRANCH-$HASH.tar.gz"
        ls openwrt/bin/targets/
        tar cfz "$TAR_NAME" -C openwrt/bin/targets/ .
        curl -u $GH_BUILD_USERNAME:$GH_BUILD_PASSWORD -T "$TAR_NAME" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/uCentral/$LOWERCASE_TARGET/"$TAR_NAME""
